/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit'

export type FundingRateState = {
  cumulativeInterestRate: bigint
  lastUpdate: bigint
  hourlyFundingDbps: bigint
}

export type FundingRateStateArgs = {
  cumulativeInterestRate: number | bigint
  lastUpdate: number | bigint
  hourlyFundingDbps: number | bigint
}

export function getFundingRateStateEncoder(): FixedSizeEncoder<FundingRateStateArgs> {
  return getStructEncoder([
    ['cumulativeInterestRate', getU128Encoder()],
    ['lastUpdate', getI64Encoder()],
    ['hourlyFundingDbps', getU64Encoder()],
  ])
}

export function getFundingRateStateDecoder(): FixedSizeDecoder<FundingRateState> {
  return getStructDecoder([
    ['cumulativeInterestRate', getU128Decoder()],
    ['lastUpdate', getI64Decoder()],
    ['hourlyFundingDbps', getU64Decoder()],
  ])
}

export function getFundingRateStateCodec(): FixedSizeCodec<
  FundingRateStateArgs,
  FundingRateState
> {
  return combineCodec(
    getFundingRateStateEncoder(),
    getFundingRateStateDecoder()
  )
}
