/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit'

export enum OracleType {
  None,
  Test,
  Pyth,
}

export type OracleTypeArgs = OracleType

export function getOracleTypeEncoder(): FixedSizeEncoder<OracleTypeArgs> {
  return getEnumEncoder(OracleType)
}

export function getOracleTypeDecoder(): FixedSizeDecoder<OracleType> {
  return getEnumDecoder(OracleType)
}

export function getOracleTypeCodec(): FixedSizeCodec<
  OracleTypeArgs,
  OracleType
> {
  return combineCodec(getOracleTypeEncoder(), getOracleTypeDecoder())
}
