/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit'

export enum RequestChange {
  None,
  Increase,
  Decrease,
}

export type RequestChangeArgs = RequestChange

export function getRequestChangeEncoder(): FixedSizeEncoder<RequestChangeArgs> {
  return getEnumEncoder(RequestChange)
}

export function getRequestChangeDecoder(): FixedSizeDecoder<RequestChange> {
  return getEnumDecoder(RequestChange)
}

export function getRequestChangeCodec(): FixedSizeCodec<
  RequestChangeArgs,
  RequestChange
> {
  return combineCodec(getRequestChangeEncoder(), getRequestChangeDecoder())
}
