//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::{BorshDeserialize, BorshSerialize};

pub const CREATE_AND_DELEGATE_STAKE_ACCOUNT_DISCRIMINATOR: [u8; 8] =
    [98, 209, 122, 27, 222, 137, 94, 134];

/// Accounts.
#[derive(Debug)]
pub struct CreateAndDelegateStakeAccount {
    pub keeper: solana_program::pubkey::Pubkey,

    pub perpetuals: solana_program::pubkey::Pubkey,

    pub pool: solana_program::pubkey::Pubkey,

    pub custody: solana_program::pubkey::Pubkey,

    pub custody_token_account: solana_program::pubkey::Pubkey,

    pub transfer_authority: solana_program::pubkey::Pubkey,

    pub stake_account: solana_program::pubkey::Pubkey,

    pub stake_info: solana_program::pubkey::Pubkey,

    pub validator_vote_account: solana_program::pubkey::Pubkey,

    pub stake_config: solana_program::pubkey::Pubkey,

    pub wsol_mint: solana_program::pubkey::Pubkey,

    pub temp_wsol_account: solana_program::pubkey::Pubkey,

    pub rent: solana_program::pubkey::Pubkey,

    pub clock: solana_program::pubkey::Pubkey,

    pub stake_history: solana_program::pubkey::Pubkey,

    pub stake_program: solana_program::pubkey::Pubkey,

    pub system_program: solana_program::pubkey::Pubkey,

    pub token_program: solana_program::pubkey::Pubkey,
}

impl CreateAndDelegateStakeAccount {
    pub fn instruction(
        &self,
        args: CreateAndDelegateStakeAccountInstructionArgs,
    ) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: CreateAndDelegateStakeAccountInstructionArgs,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(18 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.keeper,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.perpetuals,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.pool, false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.custody,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.custody_token_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.transfer_authority,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_info,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.validator_vote_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_config,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.wsol_mint,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.temp_wsol_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.rent, false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.clock, false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_history,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_program,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&CreateAndDelegateStakeAccountInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_program::instruction::Instruction {
            program_id: crate::PERPETUALS_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateAndDelegateStakeAccountInstructionData {
    discriminator: [u8; 8],
}

impl CreateAndDelegateStakeAccountInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [98, 209, 122, 27, 222, 137, 94, 134],
        }
    }
}

impl Default for CreateAndDelegateStakeAccountInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateAndDelegateStakeAccountInstructionArgs {
    pub stake_account_index: u64,
    pub stake_amount_lamports: u64,
}

/// Instruction builder for `CreateAndDelegateStakeAccount`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` keeper
///   1. `[]` perpetuals
///   2. `[writable]` pool
///   3. `[writable]` custody
///   4. `[writable]` custody_token_account
///   5. `[]` transfer_authority
///   6. `[writable]` stake_account
///   7. `[writable]` stake_info
///   8. `[]` validator_vote_account
///   9. `[]` stake_config
///   10. `[]` wsol_mint
///   11. `[writable]` temp_wsol_account
///   12. `[optional]` rent (default to `SysvarRent111111111111111111111111111111111`)
///   13. `[]` clock
///   14. `[]` stake_history
///   15. `[]` stake_program
///   16. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   17. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
#[derive(Clone, Debug, Default)]
pub struct CreateAndDelegateStakeAccountBuilder {
    keeper: Option<solana_program::pubkey::Pubkey>,
    perpetuals: Option<solana_program::pubkey::Pubkey>,
    pool: Option<solana_program::pubkey::Pubkey>,
    custody: Option<solana_program::pubkey::Pubkey>,
    custody_token_account: Option<solana_program::pubkey::Pubkey>,
    transfer_authority: Option<solana_program::pubkey::Pubkey>,
    stake_account: Option<solana_program::pubkey::Pubkey>,
    stake_info: Option<solana_program::pubkey::Pubkey>,
    validator_vote_account: Option<solana_program::pubkey::Pubkey>,
    stake_config: Option<solana_program::pubkey::Pubkey>,
    wsol_mint: Option<solana_program::pubkey::Pubkey>,
    temp_wsol_account: Option<solana_program::pubkey::Pubkey>,
    rent: Option<solana_program::pubkey::Pubkey>,
    clock: Option<solana_program::pubkey::Pubkey>,
    stake_history: Option<solana_program::pubkey::Pubkey>,
    stake_program: Option<solana_program::pubkey::Pubkey>,
    system_program: Option<solana_program::pubkey::Pubkey>,
    token_program: Option<solana_program::pubkey::Pubkey>,
    stake_account_index: Option<u64>,
    stake_amount_lamports: Option<u64>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl CreateAndDelegateStakeAccountBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn keeper(&mut self, keeper: solana_program::pubkey::Pubkey) -> &mut Self {
        self.keeper = Some(keeper);
        self
    }
    #[inline(always)]
    pub fn perpetuals(&mut self, perpetuals: solana_program::pubkey::Pubkey) -> &mut Self {
        self.perpetuals = Some(perpetuals);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: solana_program::pubkey::Pubkey) -> &mut Self {
        self.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn custody(&mut self, custody: solana_program::pubkey::Pubkey) -> &mut Self {
        self.custody = Some(custody);
        self
    }
    #[inline(always)]
    pub fn custody_token_account(
        &mut self,
        custody_token_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.custody_token_account = Some(custody_token_account);
        self
    }
    #[inline(always)]
    pub fn transfer_authority(
        &mut self,
        transfer_authority: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.transfer_authority = Some(transfer_authority);
        self
    }
    #[inline(always)]
    pub fn stake_account(&mut self, stake_account: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_account = Some(stake_account);
        self
    }
    #[inline(always)]
    pub fn stake_info(&mut self, stake_info: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_info = Some(stake_info);
        self
    }
    #[inline(always)]
    pub fn validator_vote_account(
        &mut self,
        validator_vote_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.validator_vote_account = Some(validator_vote_account);
        self
    }
    #[inline(always)]
    pub fn stake_config(&mut self, stake_config: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_config = Some(stake_config);
        self
    }
    #[inline(always)]
    pub fn wsol_mint(&mut self, wsol_mint: solana_program::pubkey::Pubkey) -> &mut Self {
        self.wsol_mint = Some(wsol_mint);
        self
    }
    #[inline(always)]
    pub fn temp_wsol_account(
        &mut self,
        temp_wsol_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.temp_wsol_account = Some(temp_wsol_account);
        self
    }
    /// `[optional account, default to 'SysvarRent111111111111111111111111111111111']`
    #[inline(always)]
    pub fn rent(&mut self, rent: solana_program::pubkey::Pubkey) -> &mut Self {
        self.rent = Some(rent);
        self
    }
    #[inline(always)]
    pub fn clock(&mut self, clock: solana_program::pubkey::Pubkey) -> &mut Self {
        self.clock = Some(clock);
        self
    }
    #[inline(always)]
    pub fn stake_history(&mut self, stake_history: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_history = Some(stake_history);
        self
    }
    #[inline(always)]
    pub fn stake_program(&mut self, stake_program: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_program = Some(stake_program);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_program::pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_program::pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn stake_account_index(&mut self, stake_account_index: u64) -> &mut Self {
        self.stake_account_index = Some(stake_account_index);
        self
    }
    #[inline(always)]
    pub fn stake_amount_lamports(&mut self, stake_amount_lamports: u64) -> &mut Self {
        self.stake_amount_lamports = Some(stake_amount_lamports);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = CreateAndDelegateStakeAccount {
            keeper: self.keeper.expect("keeper is not set"),
            perpetuals: self.perpetuals.expect("perpetuals is not set"),
            pool: self.pool.expect("pool is not set"),
            custody: self.custody.expect("custody is not set"),
            custody_token_account: self
                .custody_token_account
                .expect("custody_token_account is not set"),
            transfer_authority: self
                .transfer_authority
                .expect("transfer_authority is not set"),
            stake_account: self.stake_account.expect("stake_account is not set"),
            stake_info: self.stake_info.expect("stake_info is not set"),
            validator_vote_account: self
                .validator_vote_account
                .expect("validator_vote_account is not set"),
            stake_config: self.stake_config.expect("stake_config is not set"),
            wsol_mint: self.wsol_mint.expect("wsol_mint is not set"),
            temp_wsol_account: self
                .temp_wsol_account
                .expect("temp_wsol_account is not set"),
            rent: self.rent.unwrap_or(solana_program::pubkey!(
                "SysvarRent111111111111111111111111111111111"
            )),
            clock: self.clock.expect("clock is not set"),
            stake_history: self.stake_history.expect("stake_history is not set"),
            stake_program: self.stake_program.expect("stake_program is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_program::pubkey!("11111111111111111111111111111111")),
            token_program: self.token_program.unwrap_or(solana_program::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
        };
        let args = CreateAndDelegateStakeAccountInstructionArgs {
            stake_account_index: self
                .stake_account_index
                .clone()
                .expect("stake_account_index is not set"),
            stake_amount_lamports: self
                .stake_amount_lamports
                .clone()
                .expect("stake_amount_lamports is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `create_and_delegate_stake_account` CPI accounts.
pub struct CreateAndDelegateStakeAccountCpiAccounts<'a, 'b> {
    pub keeper: &'b solana_program::account_info::AccountInfo<'a>,

    pub perpetuals: &'b solana_program::account_info::AccountInfo<'a>,

    pub pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub custody: &'b solana_program::account_info::AccountInfo<'a>,

    pub custody_token_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub transfer_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_info: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_vote_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_config: &'b solana_program::account_info::AccountInfo<'a>,

    pub wsol_mint: &'b solana_program::account_info::AccountInfo<'a>,

    pub temp_wsol_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub rent: &'b solana_program::account_info::AccountInfo<'a>,

    pub clock: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_history: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_program: &'b solana_program::account_info::AccountInfo<'a>,

    pub system_program: &'b solana_program::account_info::AccountInfo<'a>,

    pub token_program: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `create_and_delegate_stake_account` CPI instruction.
pub struct CreateAndDelegateStakeAccountCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,

    pub keeper: &'b solana_program::account_info::AccountInfo<'a>,

    pub perpetuals: &'b solana_program::account_info::AccountInfo<'a>,

    pub pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub custody: &'b solana_program::account_info::AccountInfo<'a>,

    pub custody_token_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub transfer_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_info: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_vote_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_config: &'b solana_program::account_info::AccountInfo<'a>,

    pub wsol_mint: &'b solana_program::account_info::AccountInfo<'a>,

    pub temp_wsol_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub rent: &'b solana_program::account_info::AccountInfo<'a>,

    pub clock: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_history: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_program: &'b solana_program::account_info::AccountInfo<'a>,

    pub system_program: &'b solana_program::account_info::AccountInfo<'a>,

    pub token_program: &'b solana_program::account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: CreateAndDelegateStakeAccountInstructionArgs,
}

impl<'a, 'b> CreateAndDelegateStakeAccountCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: CreateAndDelegateStakeAccountCpiAccounts<'a, 'b>,
        args: CreateAndDelegateStakeAccountInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            keeper: accounts.keeper,
            perpetuals: accounts.perpetuals,
            pool: accounts.pool,
            custody: accounts.custody,
            custody_token_account: accounts.custody_token_account,
            transfer_authority: accounts.transfer_authority,
            stake_account: accounts.stake_account,
            stake_info: accounts.stake_info,
            validator_vote_account: accounts.validator_vote_account,
            stake_config: accounts.stake_config,
            wsol_mint: accounts.wsol_mint,
            temp_wsol_account: accounts.temp_wsol_account,
            rent: accounts.rent,
            clock: accounts.clock,
            stake_history: accounts.stake_history,
            stake_program: accounts.stake_program,
            system_program: accounts.system_program,
            token_program: accounts.token_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(18 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.keeper.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.perpetuals.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.pool.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.custody.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.custody_token_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.transfer_authority.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_info.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.validator_vote_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_config.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.wsol_mint.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.temp_wsol_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.rent.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.clock.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_history.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_program.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&CreateAndDelegateStakeAccountInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::PERPETUALS_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(19 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.keeper.clone());
        account_infos.push(self.perpetuals.clone());
        account_infos.push(self.pool.clone());
        account_infos.push(self.custody.clone());
        account_infos.push(self.custody_token_account.clone());
        account_infos.push(self.transfer_authority.clone());
        account_infos.push(self.stake_account.clone());
        account_infos.push(self.stake_info.clone());
        account_infos.push(self.validator_vote_account.clone());
        account_infos.push(self.stake_config.clone());
        account_infos.push(self.wsol_mint.clone());
        account_infos.push(self.temp_wsol_account.clone());
        account_infos.push(self.rent.clone());
        account_infos.push(self.clock.clone());
        account_infos.push(self.stake_history.clone());
        account_infos.push(self.stake_program.clone());
        account_infos.push(self.system_program.clone());
        account_infos.push(self.token_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CreateAndDelegateStakeAccount` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` keeper
///   1. `[]` perpetuals
///   2. `[writable]` pool
///   3. `[writable]` custody
///   4. `[writable]` custody_token_account
///   5. `[]` transfer_authority
///   6. `[writable]` stake_account
///   7. `[writable]` stake_info
///   8. `[]` validator_vote_account
///   9. `[]` stake_config
///   10. `[]` wsol_mint
///   11. `[writable]` temp_wsol_account
///   12. `[]` rent
///   13. `[]` clock
///   14. `[]` stake_history
///   15. `[]` stake_program
///   16. `[]` system_program
///   17. `[]` token_program
#[derive(Clone, Debug)]
pub struct CreateAndDelegateStakeAccountCpiBuilder<'a, 'b> {
    instruction: Box<CreateAndDelegateStakeAccountCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreateAndDelegateStakeAccountCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CreateAndDelegateStakeAccountCpiBuilderInstruction {
            __program: program,
            keeper: None,
            perpetuals: None,
            pool: None,
            custody: None,
            custody_token_account: None,
            transfer_authority: None,
            stake_account: None,
            stake_info: None,
            validator_vote_account: None,
            stake_config: None,
            wsol_mint: None,
            temp_wsol_account: None,
            rent: None,
            clock: None,
            stake_history: None,
            stake_program: None,
            system_program: None,
            token_program: None,
            stake_account_index: None,
            stake_amount_lamports: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn keeper(
        &mut self,
        keeper: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.keeper = Some(keeper);
        self
    }
    #[inline(always)]
    pub fn perpetuals(
        &mut self,
        perpetuals: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.perpetuals = Some(perpetuals);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn custody(
        &mut self,
        custody: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.custody = Some(custody);
        self
    }
    #[inline(always)]
    pub fn custody_token_account(
        &mut self,
        custody_token_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.custody_token_account = Some(custody_token_account);
        self
    }
    #[inline(always)]
    pub fn transfer_authority(
        &mut self,
        transfer_authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.transfer_authority = Some(transfer_authority);
        self
    }
    #[inline(always)]
    pub fn stake_account(
        &mut self,
        stake_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_account = Some(stake_account);
        self
    }
    #[inline(always)]
    pub fn stake_info(
        &mut self,
        stake_info: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_info = Some(stake_info);
        self
    }
    #[inline(always)]
    pub fn validator_vote_account(
        &mut self,
        validator_vote_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.validator_vote_account = Some(validator_vote_account);
        self
    }
    #[inline(always)]
    pub fn stake_config(
        &mut self,
        stake_config: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_config = Some(stake_config);
        self
    }
    #[inline(always)]
    pub fn wsol_mint(
        &mut self,
        wsol_mint: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.wsol_mint = Some(wsol_mint);
        self
    }
    #[inline(always)]
    pub fn temp_wsol_account(
        &mut self,
        temp_wsol_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.temp_wsol_account = Some(temp_wsol_account);
        self
    }
    #[inline(always)]
    pub fn rent(&mut self, rent: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.rent = Some(rent);
        self
    }
    #[inline(always)]
    pub fn clock(&mut self, clock: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.clock = Some(clock);
        self
    }
    #[inline(always)]
    pub fn stake_history(
        &mut self,
        stake_history: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_history = Some(stake_history);
        self
    }
    #[inline(always)]
    pub fn stake_program(
        &mut self,
        stake_program: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_program = Some(stake_program);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn stake_account_index(&mut self, stake_account_index: u64) -> &mut Self {
        self.instruction.stake_account_index = Some(stake_account_index);
        self
    }
    #[inline(always)]
    pub fn stake_amount_lamports(&mut self, stake_amount_lamports: u64) -> &mut Self {
        self.instruction.stake_amount_lamports = Some(stake_amount_lamports);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let args = CreateAndDelegateStakeAccountInstructionArgs {
            stake_account_index: self
                .instruction
                .stake_account_index
                .clone()
                .expect("stake_account_index is not set"),
            stake_amount_lamports: self
                .instruction
                .stake_amount_lamports
                .clone()
                .expect("stake_amount_lamports is not set"),
        };
        let instruction = CreateAndDelegateStakeAccountCpi {
            __program: self.instruction.__program,

            keeper: self.instruction.keeper.expect("keeper is not set"),

            perpetuals: self.instruction.perpetuals.expect("perpetuals is not set"),

            pool: self.instruction.pool.expect("pool is not set"),

            custody: self.instruction.custody.expect("custody is not set"),

            custody_token_account: self
                .instruction
                .custody_token_account
                .expect("custody_token_account is not set"),

            transfer_authority: self
                .instruction
                .transfer_authority
                .expect("transfer_authority is not set"),

            stake_account: self
                .instruction
                .stake_account
                .expect("stake_account is not set"),

            stake_info: self.instruction.stake_info.expect("stake_info is not set"),

            validator_vote_account: self
                .instruction
                .validator_vote_account
                .expect("validator_vote_account is not set"),

            stake_config: self
                .instruction
                .stake_config
                .expect("stake_config is not set"),

            wsol_mint: self.instruction.wsol_mint.expect("wsol_mint is not set"),

            temp_wsol_account: self
                .instruction
                .temp_wsol_account
                .expect("temp_wsol_account is not set"),

            rent: self.instruction.rent.expect("rent is not set"),

            clock: self.instruction.clock.expect("clock is not set"),

            stake_history: self
                .instruction
                .stake_history
                .expect("stake_history is not set"),

            stake_program: self
                .instruction
                .stake_program
                .expect("stake_program is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CreateAndDelegateStakeAccountCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    keeper: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    perpetuals: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    pool: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    custody: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    custody_token_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    transfer_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_info: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    validator_vote_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_config: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    wsol_mint: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    temp_wsol_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    rent: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    clock: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_history: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_account_index: Option<u64>,
    stake_amount_lamports: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
