/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getI32Decoder,
  getI32Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit'

export type OraclePrice = { price: bigint; exponent: number }

export type OraclePriceArgs = { price: number | bigint; exponent: number }

export function getOraclePriceEncoder(): FixedSizeEncoder<OraclePriceArgs> {
  return getStructEncoder([
    ['price', getU64Encoder()],
    ['exponent', getI32Encoder()],
  ])
}

export function getOraclePriceDecoder(): FixedSizeDecoder<OraclePrice> {
  return getStructDecoder([
    ['price', getU64Decoder()],
    ['exponent', getI32Decoder()],
  ])
}

export function getOraclePriceCodec(): FixedSizeCodec<
  OraclePriceArgs,
  OraclePrice
> {
  return combineCodec(getOraclePriceEncoder(), getOraclePriceDecoder())
}
