/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit'

export enum Side {
  None,
  Long,
  Short,
}

export type SideArgs = Side

export function getSideEncoder(): FixedSizeEncoder<SideArgs> {
  return getEnumEncoder(Side)
}

export function getSideDecoder(): FixedSizeDecoder<Side> {
  return getEnumDecoder(Side)
}

export function getSideCodec(): FixedSizeCodec<SideArgs, Side> {
  return combineCodec(getSideEncoder(), getSideDecoder())
}
