/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit'
import { PERPETUALS_PROGRAM_ADDRESS } from '../programs'
import { getAccountMetaFactory, type ResolvedAccount } from '../shared'
import {
  getRequestTypeDecoder,
  getRequestTypeEncoder,
  type RequestType,
  type RequestTypeArgs,
} from '../types'

export const CREATE_DECREASE_POSITION_REQUEST2_DISCRIMINATOR = new Uint8Array([
  105, 64, 201, 82, 250, 14, 109, 77,
])

export function getCreateDecreasePositionRequest2DiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_DECREASE_POSITION_REQUEST2_DISCRIMINATOR
  )
}

export type CreateDecreasePositionRequest2Instruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountReceivingAccount extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountPositionRequest extends string | AccountMeta<string> = string,
  TAccountPositionRequestAta extends string | AccountMeta<string> = string,
  TAccountCustody extends string | AccountMeta<string> = string,
  TAccountCustodyDovesPriceAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountCustodyPythnetPriceAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountCollateralCustody extends string | AccountMeta<string> = string,
  TAccountDesiredMint extends string | AccountMeta<string> = string,
  TAccountReferral extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountReceivingAccount extends string
        ? WritableAccount<TAccountReceivingAccount>
        : TAccountReceivingAccount,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? ReadonlyAccount<TAccountPosition>
        : TAccountPosition,
      TAccountPositionRequest extends string
        ? WritableAccount<TAccountPositionRequest>
        : TAccountPositionRequest,
      TAccountPositionRequestAta extends string
        ? WritableAccount<TAccountPositionRequestAta>
        : TAccountPositionRequestAta,
      TAccountCustody extends string
        ? ReadonlyAccount<TAccountCustody>
        : TAccountCustody,
      TAccountCustodyDovesPriceAccount extends string
        ? ReadonlyAccount<TAccountCustodyDovesPriceAccount>
        : TAccountCustodyDovesPriceAccount,
      TAccountCustodyPythnetPriceAccount extends string
        ? ReadonlyAccount<TAccountCustodyPythnetPriceAccount>
        : TAccountCustodyPythnetPriceAccount,
      TAccountCollateralCustody extends string
        ? ReadonlyAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountDesiredMint extends string
        ? ReadonlyAccount<TAccountDesiredMint>
        : TAccountDesiredMint,
      TAccountReferral extends string
        ? ReadonlyAccount<TAccountReferral>
        : TAccountReferral,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >

export type CreateDecreasePositionRequest2InstructionData = {
  discriminator: ReadonlyUint8Array
  collateralUsdDelta: bigint
  sizeUsdDelta: bigint
  requestType: RequestType
  priceSlippage: Option<bigint>
  jupiterMinimumOut: Option<bigint>
  triggerPrice: Option<bigint>
  triggerAboveThreshold: Option<boolean>
  entirePosition: Option<boolean>
  counter: bigint
}

export type CreateDecreasePositionRequest2InstructionDataArgs = {
  collateralUsdDelta: number | bigint
  sizeUsdDelta: number | bigint
  requestType: RequestTypeArgs
  priceSlippage: OptionOrNullable<number | bigint>
  jupiterMinimumOut: OptionOrNullable<number | bigint>
  triggerPrice: OptionOrNullable<number | bigint>
  triggerAboveThreshold: OptionOrNullable<boolean>
  entirePosition: OptionOrNullable<boolean>
  counter: number | bigint
}

export function getCreateDecreasePositionRequest2InstructionDataEncoder(): Encoder<CreateDecreasePositionRequest2InstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['collateralUsdDelta', getU64Encoder()],
      ['sizeUsdDelta', getU64Encoder()],
      ['requestType', getRequestTypeEncoder()],
      ['priceSlippage', getOptionEncoder(getU64Encoder())],
      ['jupiterMinimumOut', getOptionEncoder(getU64Encoder())],
      ['triggerPrice', getOptionEncoder(getU64Encoder())],
      ['triggerAboveThreshold', getOptionEncoder(getBooleanEncoder())],
      ['entirePosition', getOptionEncoder(getBooleanEncoder())],
      ['counter', getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: CREATE_DECREASE_POSITION_REQUEST2_DISCRIMINATOR,
    })
  )
}

export function getCreateDecreasePositionRequest2InstructionDataDecoder(): Decoder<CreateDecreasePositionRequest2InstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['collateralUsdDelta', getU64Decoder()],
    ['sizeUsdDelta', getU64Decoder()],
    ['requestType', getRequestTypeDecoder()],
    ['priceSlippage', getOptionDecoder(getU64Decoder())],
    ['jupiterMinimumOut', getOptionDecoder(getU64Decoder())],
    ['triggerPrice', getOptionDecoder(getU64Decoder())],
    ['triggerAboveThreshold', getOptionDecoder(getBooleanDecoder())],
    ['entirePosition', getOptionDecoder(getBooleanDecoder())],
    ['counter', getU64Decoder()],
  ])
}

export function getCreateDecreasePositionRequest2InstructionDataCodec(): Codec<
  CreateDecreasePositionRequest2InstructionDataArgs,
  CreateDecreasePositionRequest2InstructionData
> {
  return combineCodec(
    getCreateDecreasePositionRequest2InstructionDataEncoder(),
    getCreateDecreasePositionRequest2InstructionDataDecoder()
  )
}

export type CreateDecreasePositionRequest2Input<
  TAccountOwner extends string = string,
  TAccountReceivingAccount extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountPositionRequest extends string = string,
  TAccountPositionRequestAta extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyDovesPriceAccount extends string = string,
  TAccountCustodyPythnetPriceAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountDesiredMint extends string = string,
  TAccountReferral extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  owner: TransactionSigner<TAccountOwner>
  receivingAccount: Address<TAccountReceivingAccount>
  perpetuals: Address<TAccountPerpetuals>
  pool: Address<TAccountPool>
  position: Address<TAccountPosition>
  positionRequest: Address<TAccountPositionRequest>
  positionRequestAta: Address<TAccountPositionRequestAta>
  custody: Address<TAccountCustody>
  custodyDovesPriceAccount: Address<TAccountCustodyDovesPriceAccount>
  custodyPythnetPriceAccount: Address<TAccountCustodyPythnetPriceAccount>
  collateralCustody: Address<TAccountCollateralCustody>
  desiredMint: Address<TAccountDesiredMint>
  referral?: Address<TAccountReferral>
  tokenProgram?: Address<TAccountTokenProgram>
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>
  systemProgram?: Address<TAccountSystemProgram>
  eventAuthority: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
  collateralUsdDelta: CreateDecreasePositionRequest2InstructionDataArgs['collateralUsdDelta']
  sizeUsdDelta: CreateDecreasePositionRequest2InstructionDataArgs['sizeUsdDelta']
  requestType: CreateDecreasePositionRequest2InstructionDataArgs['requestType']
  priceSlippage: CreateDecreasePositionRequest2InstructionDataArgs['priceSlippage']
  jupiterMinimumOut: CreateDecreasePositionRequest2InstructionDataArgs['jupiterMinimumOut']
  triggerPrice: CreateDecreasePositionRequest2InstructionDataArgs['triggerPrice']
  triggerAboveThreshold: CreateDecreasePositionRequest2InstructionDataArgs['triggerAboveThreshold']
  entirePosition: CreateDecreasePositionRequest2InstructionDataArgs['entirePosition']
  counter: CreateDecreasePositionRequest2InstructionDataArgs['counter']
}

export function getCreateDecreasePositionRequest2Instruction<
  TAccountOwner extends string,
  TAccountReceivingAccount extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountPositionRequest extends string,
  TAccountPositionRequestAta extends string,
  TAccountCustody extends string,
  TAccountCustodyDovesPriceAccount extends string,
  TAccountCustodyPythnetPriceAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountDesiredMint extends string,
  TAccountReferral extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: CreateDecreasePositionRequest2Input<
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountPositionRequest,
    TAccountPositionRequestAta,
    TAccountCustody,
    TAccountCustodyDovesPriceAccount,
    TAccountCustodyPythnetPriceAccount,
    TAccountCollateralCustody,
    TAccountDesiredMint,
    TAccountReferral,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress }
): CreateDecreasePositionRequest2Instruction<
  TProgramAddress,
  TAccountOwner,
  TAccountReceivingAccount,
  TAccountPerpetuals,
  TAccountPool,
  TAccountPosition,
  TAccountPositionRequest,
  TAccountPositionRequestAta,
  TAccountCustody,
  TAccountCustodyDovesPriceAccount,
  TAccountCustodyPythnetPriceAccount,
  TAccountCollateralCustody,
  TAccountDesiredMint,
  TAccountReferral,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: true },
    receivingAccount: {
      value: input.receivingAccount ?? null,
      isWritable: true,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    position: { value: input.position ?? null, isWritable: false },
    positionRequest: { value: input.positionRequest ?? null, isWritable: true },
    positionRequestAta: {
      value: input.positionRequestAta ?? null,
      isWritable: true,
    },
    custody: { value: input.custody ?? null, isWritable: false },
    custodyDovesPriceAccount: {
      value: input.custodyDovesPriceAccount ?? null,
      isWritable: false,
    },
    custodyPythnetPriceAccount: {
      value: input.custodyPythnetPriceAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: false,
    },
    desiredMint: { value: input.desiredMint ?? null, isWritable: false },
    referral: { value: input.referral ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >

  // Original args.
  const args = { ...input }

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  const instruction = {
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.receivingAccount),
      getAccountMeta(accounts.perpetuals),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.positionRequest),
      getAccountMeta(accounts.positionRequestAta),
      getAccountMeta(accounts.custody),
      getAccountMeta(accounts.custodyDovesPriceAccount),
      getAccountMeta(accounts.custodyPythnetPriceAccount),
      getAccountMeta(accounts.collateralCustody),
      getAccountMeta(accounts.desiredMint),
      getAccountMeta(accounts.referral),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    programAddress,
    data: getCreateDecreasePositionRequest2InstructionDataEncoder().encode(
      args as CreateDecreasePositionRequest2InstructionDataArgs
    ),
  } as CreateDecreasePositionRequest2Instruction<
    TProgramAddress,
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountPositionRequest,
    TAccountPositionRequestAta,
    TAccountCustody,
    TAccountCustodyDovesPriceAccount,
    TAccountCustodyPythnetPriceAccount,
    TAccountCollateralCustody,
    TAccountDesiredMint,
    TAccountReferral,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >

  return instruction
}

export type ParsedCreateDecreasePositionRequest2Instruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>
  accounts: {
    owner: TAccountMetas[0]
    receivingAccount: TAccountMetas[1]
    perpetuals: TAccountMetas[2]
    pool: TAccountMetas[3]
    position: TAccountMetas[4]
    positionRequest: TAccountMetas[5]
    positionRequestAta: TAccountMetas[6]
    custody: TAccountMetas[7]
    custodyDovesPriceAccount: TAccountMetas[8]
    custodyPythnetPriceAccount: TAccountMetas[9]
    collateralCustody: TAccountMetas[10]
    desiredMint: TAccountMetas[11]
    referral?: TAccountMetas[12] | undefined
    tokenProgram: TAccountMetas[13]
    associatedTokenProgram: TAccountMetas[14]
    systemProgram: TAccountMetas[15]
    eventAuthority: TAccountMetas[16]
    program: TAccountMetas[17]
  }
  data: CreateDecreasePositionRequest2InstructionData
}

export function parseCreateDecreasePositionRequest2Instruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCreateDecreasePositionRequest2Instruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 18) {
    // TODO: Coded error.
    throw new Error('Not enough accounts')
  }
  let accountIndex = 0
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!
    accountIndex += 1
    return accountMeta
  }
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount()
    return accountMeta.address === PERPETUALS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta
  }
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      receivingAccount: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      positionRequest: getNextAccount(),
      positionRequestAta: getNextAccount(),
      custody: getNextAccount(),
      custodyDovesPriceAccount: getNextAccount(),
      custodyPythnetPriceAccount: getNextAccount(),
      collateralCustody: getNextAccount(),
      desiredMint: getNextAccount(),
      referral: getNextOptionalAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getCreateDecreasePositionRequest2InstructionDataDecoder().decode(
      instruction.data
    ),
  }
}
