/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit'
import { PERPETUALS_PROGRAM_ADDRESS } from '../programs'
import { getAccountMetaFactory, type ResolvedAccount } from '../shared'

export const INSTANT_DECREASE_POSITION_DISCRIMINATOR = new Uint8Array([
  46, 23, 240, 44, 30, 138, 94, 140,
])

export function getInstantDecreasePositionDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INSTANT_DECREASE_POSITION_DISCRIMINATOR
  )
}

export type InstantDecreasePositionInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountKeeper extends string | AccountMeta<string> = string,
  TAccountApiKeeper extends string | AccountMeta<string> = string,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountReceivingAccount extends string | AccountMeta<string> = string,
  TAccountTransferAuthority extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountCustody extends string | AccountMeta<string> = string,
  TAccountCustodyDovesPriceAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountCustodyPythnetPriceAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountCollateralCustody extends string | AccountMeta<string> = string,
  TAccountCollateralCustodyDovesPriceAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountCollateralCustodyPythnetPriceAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountCollateralCustodyTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountDesiredMint extends string | AccountMeta<string> = string,
  TAccountReferral extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountKeeper extends string
        ? ReadonlySignerAccount<TAccountKeeper> &
            AccountSignerMeta<TAccountKeeper>
        : TAccountKeeper,
      TAccountApiKeeper extends string
        ? ReadonlySignerAccount<TAccountApiKeeper> &
            AccountSignerMeta<TAccountApiKeeper>
        : TAccountApiKeeper,
      TAccountOwner extends string
        ? WritableSignerAccount<TAccountOwner> &
            AccountSignerMeta<TAccountOwner>
        : TAccountOwner,
      TAccountReceivingAccount extends string
        ? WritableAccount<TAccountReceivingAccount>
        : TAccountReceivingAccount,
      TAccountTransferAuthority extends string
        ? ReadonlyAccount<TAccountTransferAuthority>
        : TAccountTransferAuthority,
      TAccountPerpetuals extends string
        ? ReadonlyAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountCustody extends string
        ? WritableAccount<TAccountCustody>
        : TAccountCustody,
      TAccountCustodyDovesPriceAccount extends string
        ? ReadonlyAccount<TAccountCustodyDovesPriceAccount>
        : TAccountCustodyDovesPriceAccount,
      TAccountCustodyPythnetPriceAccount extends string
        ? ReadonlyAccount<TAccountCustodyPythnetPriceAccount>
        : TAccountCustodyPythnetPriceAccount,
      TAccountCollateralCustody extends string
        ? WritableAccount<TAccountCollateralCustody>
        : TAccountCollateralCustody,
      TAccountCollateralCustodyDovesPriceAccount extends string
        ? ReadonlyAccount<TAccountCollateralCustodyDovesPriceAccount>
        : TAccountCollateralCustodyDovesPriceAccount,
      TAccountCollateralCustodyPythnetPriceAccount extends string
        ? ReadonlyAccount<TAccountCollateralCustodyPythnetPriceAccount>
        : TAccountCollateralCustodyPythnetPriceAccount,
      TAccountCollateralCustodyTokenAccount extends string
        ? WritableAccount<TAccountCollateralCustodyTokenAccount>
        : TAccountCollateralCustodyTokenAccount,
      TAccountDesiredMint extends string
        ? ReadonlyAccount<TAccountDesiredMint>
        : TAccountDesiredMint,
      TAccountReferral extends string
        ? ReadonlyAccount<TAccountReferral>
        : TAccountReferral,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >

export type InstantDecreasePositionInstructionData = {
  discriminator: ReadonlyUint8Array
  collateralUsdDelta: bigint
  sizeUsdDelta: bigint
  priceSlippage: bigint
  entirePosition: Option<boolean>
  requestTime: bigint
}

export type InstantDecreasePositionInstructionDataArgs = {
  collateralUsdDelta: number | bigint
  sizeUsdDelta: number | bigint
  priceSlippage: number | bigint
  entirePosition: OptionOrNullable<boolean>
  requestTime: number | bigint
}

export function getInstantDecreasePositionInstructionDataEncoder(): Encoder<InstantDecreasePositionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['collateralUsdDelta', getU64Encoder()],
      ['sizeUsdDelta', getU64Encoder()],
      ['priceSlippage', getU64Encoder()],
      ['entirePosition', getOptionEncoder(getBooleanEncoder())],
      ['requestTime', getI64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INSTANT_DECREASE_POSITION_DISCRIMINATOR,
    })
  )
}

export function getInstantDecreasePositionInstructionDataDecoder(): Decoder<InstantDecreasePositionInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['collateralUsdDelta', getU64Decoder()],
    ['sizeUsdDelta', getU64Decoder()],
    ['priceSlippage', getU64Decoder()],
    ['entirePosition', getOptionDecoder(getBooleanDecoder())],
    ['requestTime', getI64Decoder()],
  ])
}

export function getInstantDecreasePositionInstructionDataCodec(): Codec<
  InstantDecreasePositionInstructionDataArgs,
  InstantDecreasePositionInstructionData
> {
  return combineCodec(
    getInstantDecreasePositionInstructionDataEncoder(),
    getInstantDecreasePositionInstructionDataDecoder()
  )
}

export type InstantDecreasePositionInput<
  TAccountKeeper extends string = string,
  TAccountApiKeeper extends string = string,
  TAccountOwner extends string = string,
  TAccountReceivingAccount extends string = string,
  TAccountTransferAuthority extends string = string,
  TAccountPerpetuals extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountCustody extends string = string,
  TAccountCustodyDovesPriceAccount extends string = string,
  TAccountCustodyPythnetPriceAccount extends string = string,
  TAccountCollateralCustody extends string = string,
  TAccountCollateralCustodyDovesPriceAccount extends string = string,
  TAccountCollateralCustodyPythnetPriceAccount extends string = string,
  TAccountCollateralCustodyTokenAccount extends string = string,
  TAccountDesiredMint extends string = string,
  TAccountReferral extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountProgram extends string = string,
> = {
  keeper: TransactionSigner<TAccountKeeper>
  apiKeeper: TransactionSigner<TAccountApiKeeper>
  owner: TransactionSigner<TAccountOwner>
  receivingAccount: Address<TAccountReceivingAccount>
  transferAuthority: Address<TAccountTransferAuthority>
  perpetuals: Address<TAccountPerpetuals>
  pool: Address<TAccountPool>
  position: Address<TAccountPosition>
  custody: Address<TAccountCustody>
  custodyDovesPriceAccount: Address<TAccountCustodyDovesPriceAccount>
  custodyPythnetPriceAccount: Address<TAccountCustodyPythnetPriceAccount>
  collateralCustody: Address<TAccountCollateralCustody>
  collateralCustodyDovesPriceAccount: Address<TAccountCollateralCustodyDovesPriceAccount>
  collateralCustodyPythnetPriceAccount: Address<TAccountCollateralCustodyPythnetPriceAccount>
  collateralCustodyTokenAccount: Address<TAccountCollateralCustodyTokenAccount>
  desiredMint: Address<TAccountDesiredMint>
  referral?: Address<TAccountReferral>
  tokenProgram?: Address<TAccountTokenProgram>
  associatedTokenProgram: Address<TAccountAssociatedTokenProgram>
  systemProgram?: Address<TAccountSystemProgram>
  eventAuthority: Address<TAccountEventAuthority>
  program: Address<TAccountProgram>
  collateralUsdDelta: InstantDecreasePositionInstructionDataArgs['collateralUsdDelta']
  sizeUsdDelta: InstantDecreasePositionInstructionDataArgs['sizeUsdDelta']
  priceSlippage: InstantDecreasePositionInstructionDataArgs['priceSlippage']
  entirePosition: InstantDecreasePositionInstructionDataArgs['entirePosition']
  requestTime: InstantDecreasePositionInstructionDataArgs['requestTime']
}

export function getInstantDecreasePositionInstruction<
  TAccountKeeper extends string,
  TAccountApiKeeper extends string,
  TAccountOwner extends string,
  TAccountReceivingAccount extends string,
  TAccountTransferAuthority extends string,
  TAccountPerpetuals extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountCustody extends string,
  TAccountCustodyDovesPriceAccount extends string,
  TAccountCustodyPythnetPriceAccount extends string,
  TAccountCollateralCustody extends string,
  TAccountCollateralCustodyDovesPriceAccount extends string,
  TAccountCollateralCustodyPythnetPriceAccount extends string,
  TAccountCollateralCustodyTokenAccount extends string,
  TAccountDesiredMint extends string,
  TAccountReferral extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TAccountEventAuthority extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: InstantDecreasePositionInput<
    TAccountKeeper,
    TAccountApiKeeper,
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountCustodyDovesPriceAccount,
    TAccountCustodyPythnetPriceAccount,
    TAccountCollateralCustody,
    TAccountCollateralCustodyDovesPriceAccount,
    TAccountCollateralCustodyPythnetPriceAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountDesiredMint,
    TAccountReferral,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InstantDecreasePositionInstruction<
  TProgramAddress,
  TAccountKeeper,
  TAccountApiKeeper,
  TAccountOwner,
  TAccountReceivingAccount,
  TAccountTransferAuthority,
  TAccountPerpetuals,
  TAccountPool,
  TAccountPosition,
  TAccountCustody,
  TAccountCustodyDovesPriceAccount,
  TAccountCustodyPythnetPriceAccount,
  TAccountCollateralCustody,
  TAccountCollateralCustodyDovesPriceAccount,
  TAccountCollateralCustodyPythnetPriceAccount,
  TAccountCollateralCustodyTokenAccount,
  TAccountDesiredMint,
  TAccountReferral,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram,
  TAccountEventAuthority,
  TAccountProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    keeper: { value: input.keeper ?? null, isWritable: false },
    apiKeeper: { value: input.apiKeeper ?? null, isWritable: false },
    owner: { value: input.owner ?? null, isWritable: true },
    receivingAccount: {
      value: input.receivingAccount ?? null,
      isWritable: true,
    },
    transferAuthority: {
      value: input.transferAuthority ?? null,
      isWritable: false,
    },
    perpetuals: { value: input.perpetuals ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    custody: { value: input.custody ?? null, isWritable: true },
    custodyDovesPriceAccount: {
      value: input.custodyDovesPriceAccount ?? null,
      isWritable: false,
    },
    custodyPythnetPriceAccount: {
      value: input.custodyPythnetPriceAccount ?? null,
      isWritable: false,
    },
    collateralCustody: {
      value: input.collateralCustody ?? null,
      isWritable: true,
    },
    collateralCustodyDovesPriceAccount: {
      value: input.collateralCustodyDovesPriceAccount ?? null,
      isWritable: false,
    },
    collateralCustodyPythnetPriceAccount: {
      value: input.collateralCustodyPythnetPriceAccount ?? null,
      isWritable: false,
    },
    collateralCustodyTokenAccount: {
      value: input.collateralCustodyTokenAccount ?? null,
      isWritable: true,
    },
    desiredMint: { value: input.desiredMint ?? null, isWritable: false },
    referral: { value: input.referral ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    program: { value: input.program ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >

  // Original args.
  const args = { ...input }

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  const instruction = {
    accounts: [
      getAccountMeta(accounts.keeper),
      getAccountMeta(accounts.apiKeeper),
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.receivingAccount),
      getAccountMeta(accounts.transferAuthority),
      getAccountMeta(accounts.perpetuals),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.position),
      getAccountMeta(accounts.custody),
      getAccountMeta(accounts.custodyDovesPriceAccount),
      getAccountMeta(accounts.custodyPythnetPriceAccount),
      getAccountMeta(accounts.collateralCustody),
      getAccountMeta(accounts.collateralCustodyDovesPriceAccount),
      getAccountMeta(accounts.collateralCustodyPythnetPriceAccount),
      getAccountMeta(accounts.collateralCustodyTokenAccount),
      getAccountMeta(accounts.desiredMint),
      getAccountMeta(accounts.referral),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.eventAuthority),
      getAccountMeta(accounts.program),
    ],
    programAddress,
    data: getInstantDecreasePositionInstructionDataEncoder().encode(
      args as InstantDecreasePositionInstructionDataArgs
    ),
  } as InstantDecreasePositionInstruction<
    TProgramAddress,
    TAccountKeeper,
    TAccountApiKeeper,
    TAccountOwner,
    TAccountReceivingAccount,
    TAccountTransferAuthority,
    TAccountPerpetuals,
    TAccountPool,
    TAccountPosition,
    TAccountCustody,
    TAccountCustodyDovesPriceAccount,
    TAccountCustodyPythnetPriceAccount,
    TAccountCollateralCustody,
    TAccountCollateralCustodyDovesPriceAccount,
    TAccountCollateralCustodyPythnetPriceAccount,
    TAccountCollateralCustodyTokenAccount,
    TAccountDesiredMint,
    TAccountReferral,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram,
    TAccountEventAuthority,
    TAccountProgram
  >

  return instruction
}

export type ParsedInstantDecreasePositionInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>
  accounts: {
    keeper: TAccountMetas[0]
    apiKeeper: TAccountMetas[1]
    owner: TAccountMetas[2]
    receivingAccount: TAccountMetas[3]
    transferAuthority: TAccountMetas[4]
    perpetuals: TAccountMetas[5]
    pool: TAccountMetas[6]
    position: TAccountMetas[7]
    custody: TAccountMetas[8]
    custodyDovesPriceAccount: TAccountMetas[9]
    custodyPythnetPriceAccount: TAccountMetas[10]
    collateralCustody: TAccountMetas[11]
    collateralCustodyDovesPriceAccount: TAccountMetas[12]
    collateralCustodyPythnetPriceAccount: TAccountMetas[13]
    collateralCustodyTokenAccount: TAccountMetas[14]
    desiredMint: TAccountMetas[15]
    referral?: TAccountMetas[16] | undefined
    tokenProgram: TAccountMetas[17]
    associatedTokenProgram: TAccountMetas[18]
    systemProgram: TAccountMetas[19]
    eventAuthority: TAccountMetas[20]
    program: TAccountMetas[21]
  }
  data: InstantDecreasePositionInstructionData
}

export function parseInstantDecreasePositionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInstantDecreasePositionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 22) {
    // TODO: Coded error.
    throw new Error('Not enough accounts')
  }
  let accountIndex = 0
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!
    accountIndex += 1
    return accountMeta
  }
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount()
    return accountMeta.address === PERPETUALS_PROGRAM_ADDRESS
      ? undefined
      : accountMeta
  }
  return {
    programAddress: instruction.programAddress,
    accounts: {
      keeper: getNextAccount(),
      apiKeeper: getNextAccount(),
      owner: getNextAccount(),
      receivingAccount: getNextAccount(),
      transferAuthority: getNextAccount(),
      perpetuals: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      custody: getNextAccount(),
      custodyDovesPriceAccount: getNextAccount(),
      custodyPythnetPriceAccount: getNextAccount(),
      collateralCustody: getNextAccount(),
      collateralCustodyDovesPriceAccount: getNextAccount(),
      collateralCustodyPythnetPriceAccount: getNextAccount(),
      collateralCustodyTokenAccount: getNextAccount(),
      desiredMint: getNextAccount(),
      referral: getNextOptionalAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
      eventAuthority: getNextAccount(),
      program: getNextAccount(),
    },
    data: getInstantDecreasePositionInstructionDataDecoder().decode(
      instruction.data
    ),
  }
}
