/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit'
import { PERPETUALS_PROGRAM_ADDRESS } from '../programs'
import { getAccountMetaFactory, type ResolvedAccount } from '../shared'

export const TRANSFER_ADMIN_DISCRIMINATOR = new Uint8Array([
  42, 242, 66, 106, 228, 10, 111, 156,
])

export function getTransferAdminDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSFER_ADMIN_DISCRIMINATOR
  )
}

export type TransferAdminInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountNewAdmin extends string | AccountMeta<string> = string,
  TAccountPerpetuals extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? ReadonlySignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountNewAdmin extends string
        ? ReadonlyAccount<TAccountNewAdmin>
        : TAccountNewAdmin,
      TAccountPerpetuals extends string
        ? WritableAccount<TAccountPerpetuals>
        : TAccountPerpetuals,
      ...TRemainingAccounts,
    ]
  >

export type TransferAdminInstructionData = { discriminator: ReadonlyUint8Array }

export type TransferAdminInstructionDataArgs = {}

export function getTransferAdminInstructionDataEncoder(): FixedSizeEncoder<TransferAdminInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: TRANSFER_ADMIN_DISCRIMINATOR })
  )
}

export function getTransferAdminInstructionDataDecoder(): FixedSizeDecoder<TransferAdminInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ])
}

export function getTransferAdminInstructionDataCodec(): FixedSizeCodec<
  TransferAdminInstructionDataArgs,
  TransferAdminInstructionData
> {
  return combineCodec(
    getTransferAdminInstructionDataEncoder(),
    getTransferAdminInstructionDataDecoder()
  )
}

export type TransferAdminInput<
  TAccountAdmin extends string = string,
  TAccountNewAdmin extends string = string,
  TAccountPerpetuals extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>
  newAdmin: Address<TAccountNewAdmin>
  perpetuals: Address<TAccountPerpetuals>
}

export function getTransferAdminInstruction<
  TAccountAdmin extends string,
  TAccountNewAdmin extends string,
  TAccountPerpetuals extends string,
  TProgramAddress extends Address = typeof PERPETUALS_PROGRAM_ADDRESS,
>(
  input: TransferAdminInput<
    TAccountAdmin,
    TAccountNewAdmin,
    TAccountPerpetuals
  >,
  config?: { programAddress?: TProgramAddress }
): TransferAdminInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountNewAdmin,
  TAccountPerpetuals
> {
  // Program address.
  const programAddress = config?.programAddress ?? PERPETUALS_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: false },
    newAdmin: { value: input.newAdmin ?? null, isWritable: false },
    perpetuals: { value: input.perpetuals ?? null, isWritable: true },
  }
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  const instruction = {
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.newAdmin),
      getAccountMeta(accounts.perpetuals),
    ],
    programAddress,
    data: getTransferAdminInstructionDataEncoder().encode({}),
  } as TransferAdminInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountNewAdmin,
    TAccountPerpetuals
  >

  return instruction
}

export type ParsedTransferAdminInstruction<
  TProgram extends string = typeof PERPETUALS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>
  accounts: {
    admin: TAccountMetas[0]
    newAdmin: TAccountMetas[1]
    perpetuals: TAccountMetas[2]
  }
  data: TransferAdminInstructionData
}

export function parseTransferAdminInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedTransferAdminInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error('Not enough accounts')
  }
  let accountIndex = 0
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!
    accountIndex += 1
    return accountMeta
  }
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      newAdmin: getNextAccount(),
      perpetuals: getNextAccount(),
    },
    data: getTransferAdminInstructionDataDecoder().decode(instruction.data),
  }
}
